### PR TITLE
Follow Button Functionality and Modals

### LINKED ISSUE #58: Add following, view following/followers

### PR DESCRIPTION
**Pull request by kimberlym4488**
- [x] Useeffect sets sets button state at page load.
- [x] Checks if user is already following that closet owner.
- [x] Back end linked up to add/remove from user and closet owner followers/following
- [x] Follower/following modals open on click.

https://www.loom.com/share/26af9b6181674f74b586eb93e382b8c9

Resolves #58

### CODE REVIEW

**Review by MikiWolfe — APPROVED** [review]
Looks great!

**Comment by jmichaelbrown8** [comment]
Looks great! Check out my latest pr for a strategy to prevent cached data from holding on to the old followers state.

You can basically add `{ fetchPolicy: "no-cache" }` to the options object in the useQuery hook to make sure it always gets the latest data.

**Review by jmichaelbrown8 — APPROVED** [review]

**Comment by jmichaelbrown8** [comment]
Oh, and we also need a unique key on the list of followers and following to get rid of that react warning in the console.

**Comment by jmichaelbrown8** [comment]
Oh, and I just realized the following and followers is always grabbing the logged in user's followers and following, not the profile of the user we're viewing--I think this is fine for the demo, but would want to change that eventually.

**Pull request merged**
